export const amenitiesList = [
  "Access via exterior corridors",
  "Bathroom phone",
  "Climate control",
  "Courtyard view",
  "Extra towels/bedding",
  "Hair dryer",
  "Individually decorated",
  "In-room safe (laptop compatible)",
  "Makeup/shaving mirror",
  "Refrigerator",
  "Shower/tub combination",
  "Welcome amenities",
  "Air conditioning",
  "Blackout drapes/curtains",
  "Complimentary toiletries",
  "Cribs/infant beds available",
  "Dial-up Internet access (surcharge)",
  "Free Wi-Fi",
  "Handheld showerhead",
  "Individually furnished",
  "Iron/ironing board (on request)",
  "Minibar",
  "Satellite TV service",
  "Slippers",
  "Bathrobes",
  "City view",
  "Complimentary weekday newspaper",
  "Daily housekeeping",
  "Direct-dial phone",
  "Free wired high-speed Internet",
  "Hypo-allergenic bedding available",
  "In-room childcare (surcharge)",
  "LCD TV",
  "Private bathroom",
  "Wake-up calls",
];
