export const roomTypes = [
    "One-Bedroom",
    "Two-Bedroom Apartment",
    "Studio Apartment With Creek View",
    "Executive Two-Bedrooms Apartment",
    "Double or Twin Rooms",
    "Triple Rooms",
    "Superior Double",
    "Junior Suites",
    "Classic Double or Twin Rooms",
    "Interconnecting Classic Room",
    "Delux Room",
    "Double Deluxe Rooms",
    "Royal Platinum Suite",
    "Standard Room",
    "One-Bedroom Executive",
    "Studio Premier",
    "Executive Suite",
    "Extra Bed / Child",
    "Presidential Suite",
    "Family Room & Twin / Large Superior",
    "Garden View Room",
    "Ocean View Room",
    "Classic Double Room",
    "Classic Single Room",
    "Superior Single View",
    "Superior Park View",
    "Single",
    "Double",
    "Guest Rooms",
    "Acessible Rooms",   
]
