export const SELECT_ITEM = "SELECT_ITEM";
export const DESELECT_ITEM = "DESELECT_ITEM";
export const CLEAR_SELECT_ITEM = "CLEAR_SELECT_ITEM";
export const ROUTES_SEARCH = "ROUTES_SEARCH";
export const CLEAR_ROUTES_SEARCH = "CLEAR_ROUTES_SEARCH";