export const LIST_HOTELS = "LIST_HOTELS";
export const DELETE_CHECKED = "DELETE_CHECKED";
export const SET_HOTELS_PAGE_OR_LIMIT = "SET_HOTELS_PAGE_OR_LIMIT";
export const SET_HOTELS_TOTAL_PAGES = "SET_HOTELS_TOTAL_PAGES";
export const GET_HOTELS_PAGINATE = "GET_HOTELS_PAGINATE";
export const GET_HOTELS_SIZE = "GET_HOTELS_SIZE";
