export const GET_ALL_ROOMS = "GET_ALL_ROOMS";
export const GET_ROOMS_PAGINATE = "GET_ALL_ROOM_PAGINATE";

export const GET_ROOMS_FILTER = "GET_ROOMS_FILTER";
export const GET_ROOMS_IS_CLICKED = "GET_ROOMS_IS_CLICKED";

export const FILTER_ROOMS = "CHANGE_ROOMS_FILTER";
export const CHANGE_ROOMS_FILTER_ACTIVE = "CHANGE_ROOMS_FILTER_ACTIVE";
