export const GET_ALL_ROOMS = "GET_ALL_ROOMS";
export const GET_ROOMS_PAGINATE = "GET_ALL_ROOM_PAGINATE";
export const GET_ROOMS_SIZE = "GET_ROOMS_SIZE";

export const GET_ROOMS_FILTER = "GET_ROOMS_FILTER";
export const GET_ROOMS_IS_CLICKED = "GET_ROOMS_IS_CLICKED";

export const FILTER_ROOMS = "CHANGE_ROOMS_FILTER";
export const CHANGE_ROOMS_FILTER_ACTIVE = "CHANGE_ROOMS_FILTER_ACTIVE";

export const DELETE_ROOM = "DELETE_ROOM";

export const SET_ROOMS_PAGE_OR_LIMIT = "SET_ROOMS_PAGE_OR_LIMIT";
export const SET_ROOMS_TOTAL_PAGES = "SET_TOTAL_PAGES";

export const ADD_ROOMS_CHECKBOX = "ADD_ROOMS_CHECKBOX";
export const REMOVE_ROOMS_CHECKBOX = "REMOVE_ROOMS_CHECKBOX";
